name: numbers
description: Generates a number.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dio: ^3.0.7
  dio_cookie_manager: ^1.0.0
  json_annotation: ^3.0.0
  logger: ^0.7.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  json_serializable: ^3.2.3

flutter:
  uses-material-design: true
  assets:
    - solar-system.png
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Black.ttf
        - asset: fonts/Rubik-Bold.ttf
        - asset: fonts/Rubik-Light.ttf
        - asset: fonts/Rubik-Medium.ttf
        - asset: fonts/Rubik-Regular.ttf
